# Welcome to Jekyll!

# Site settings
title: Personal Development Progress Tracker
email: hello@samgoddard.co.uk
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: samuelgoddard
github_username:  samuelgoddard

# Build settings
markdown: kramdown
plugins:

livereload: true     # You no longer need to include --livereload

collections:
  gists:
    output: true
    permalink: /:collection/:name
